'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tales_of_Vesperia_Save_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgEstelle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgEstelle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgJudith() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgJudith", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgKarol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgKarol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRaven() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRaven", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRepede() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRepede", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgRita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgRita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgYuri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgYuri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tales of Vesperia Save Editor.
        '''</summary>
        Friend ReadOnly Property MainFormTitle() As String
            Get
                Return ResourceManager.GetString("MainFormTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The value you entered is invalid. If you entered a value that is too high, it has been reset to the maximum allowed value..
        '''</summary>
        Friend ReadOnly Property msgBoxErrorInvalidInput() As String
            Get
                Return ResourceManager.GetString("msgBoxErrorInvalidInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while parsing the package..
        '''</summary>
        Friend ReadOnly Property msgBoxErrorOpenParsingFailure() As String
            Get
                Return ResourceManager.GetString("msgBoxErrorOpenParsingFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while extracted the save data from the CON File.
        '''</summary>
        Friend ReadOnly Property msgBoxErrorOpenSaveExtractFailure() As String
            Get
                Return ResourceManager.GetString("msgBoxErrorOpenSaveExtractFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could now locate save in CON File.
        '''</summary>
        Friend ReadOnly Property msgBoxErrorOpenSaveMissing() As String
            Get
                Return ResourceManager.GetString("msgBoxErrorOpenSaveMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an error populating the form with values read from the save..
        '''</summary>
        Friend ReadOnly Property msgBoxErrorPopulateValuesFailed() As String
            Get
                Return ResourceManager.GetString("msgBoxErrorPopulateValuesFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while injecting the save data back into the CON File.
        '''</summary>
        Friend ReadOnly Property msgBoxErrorSaveCONInjectionFailure() As String
            Get
                Return ResourceManager.GetString("msgBoxErrorSaveCONInjectionFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to hash/sign save.
        '''</summary>
        Friend ReadOnly Property msgBoxErrorSaveReHashFailure() As String
            Get
                Return ResourceManager.GetString("msgBoxErrorSaveReHashFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Loaded Successfully.
        '''</summary>
        Friend ReadOnly Property msgBoxOpenSuccess() As String
            Get
                Return ResourceManager.GetString("msgBoxOpenSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Modded Successfully.
        '''</summary>
        Friend ReadOnly Property msgBoxSaveSuccess() As String
            Get
                Return ResourceManager.GetString("msgBoxSaveSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error opening gamesave.
        '''</summary>
        Friend ReadOnly Property msgBoxTitleErrorOpen() As String
            Get
                Return ResourceManager.GetString("msgBoxTitleErrorOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving gamesave.
        '''</summary>
        Friend ReadOnly Property msgBoxTitleErrorSave() As String
            Get
                Return ResourceManager.GetString("msgBoxTitleErrorSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property TOV_Icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("TOV_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
